name: first

on: push

jobs:
  job1:
    name: first job1
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        uses: actions/checkout@v2

      - name: Step 2
        run: env | sort

  job2:
    name: first job1
    runs-on: windows-latest

    steps:
      - name: Step one
        uses: actions/checkout@v2

      - name: Step two
        run: 'Get-ChildItem Env: | Sort-Object Name'
